name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Project Setup # Use the custom reusable action.
        uses: ./.github/actions/setup

      - name: Install pipx
        run: python -m pip install --upgrade pipx

      - name: Install Poetry
        run: pipx install poetry
        shell: bash

      - name: Install Dependencies
        run: poetry install

      - name: Run Tests
        run: poetry run pytest tests/

      - name: Run Linting
        run: poetry run ruff check src/ tasks.py tests/

      - name: Run Typing Checks
        run: poetry run mypy src/ tasks.py tests/

      - name: Run Tests # Run tests using the invoke task.
        run: poetry run invoke test

      - name: Run Linting # Run linting using the invoke task.
        run: poetry run invoke lint

      - name: Run Typing Checks # Run typing checks using the invoke task.
        run: poetry run invoke type